[workspace]
resolver = "2"
members = ["kernel", "server", "engine-py"]

[workspace.dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "time", "signal"] }
tokio-postgres = { version = "0.7", features = ["with-chrono-0_4", "with-serde_json-1"] }
sea-query = { version = "1.0", features = ["backend-postgres", "with-chrono", "with-json", "postgres-array"] }
sea-query-postgres = { version = "0.6", features = ["with-chrono", "with-json", "postgres-array"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
chrono = { version = "0.4", default-features = false, features = ["std", "serde"] }
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

[profile.release]
lto = true
codegen-units = 1
